### PR TITLE
updated the contact page layout

### PR DESCRIPTION
**Pull request by DivyaJyothi9**
Improve Contact Page Layout and Background

Reduce the gap between the "Contact Us" heading and the contact information for a more cohesive layout.

Screenshot (304)

Change the background color of the Contact page to light cyan that aligns with the theme of the other sections.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @DivyaJyothi9 please resolve merge conflicts.

**Comment by DivyaJyothi9** [comment]
@gauravsingh1281 Sir, I resolved the conflicts.. Could u kindly check it!!
Thank you!!

**Comment by gauravsingh1281** [comment]
Hey @DivyaJyothi9 I merged the changes you made but no changes are visible.

**Comment by DivyaJyothi9** [comment]
@gauravsingh1281 , I have just checked it..the changes have been showed 
Screenshot (311)

otherwise can i create a pull request again @gauravsingh1281 ..so we can identify the changes.

**Comment by gauravsingh1281** [comment]
Hey @DivyaJyothi9 raise another PR.

**Comment by DivyaJyothi9** [comment]
Sir, I have created PR #223
Thank you @gauravsingh1281

**Pull request merged**
