### PR TITLE
Added show password button #280

### LINKED ISSUE #280: Show password button
image
image
Signin and signup page lacks show password buttons. I want to work on this issue. Assign me this task under gssoc-ext, hacktoberfest-accepted and level2 labels @gauravsingh1281

### PR DESCRIPTION
**Pull request by devarsheecodess**
### 🚀 Pull Request

**Description**  
I have added show password button two login and register page.

**Related Issue**  
Closes #280 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🐛 Bug fix  
- [x] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [x] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by devarsheecodess** [comment]
@gauravsingh1281 add labels here too same as issue #280

**Comment by gauravsingh1281** [comment]
Hey @devarsheecodess please resolve the merge conflicts.

**Comment by devarsheecodess** [comment]
@gauravsingh1281 done

**Review by devarsheecodess — COMMENTED** [review]
.

**Comment by devarsheecodess** [comment]
@gauravsingh1281 merge my PR and also add labels here too

**Comment by devarsheecodess** [comment]
@gauravsingh1281 ?

**Comment by gauravsingh1281** [comment]
Hey @devarsheecodess in confirm the password input field icon is missing fix this.

**Comment by gauravsingh1281** [comment]
Hey @devarsheecodess, your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify.

**Comment by devarsheecodess** [comment]
> Hey @devarsheecodess, your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify.

I am trying to figure out what actually went wrong, because the code i have written is correct 🥲🥲

**Comment by gauravsingh1281** [comment]
Screenshot 2024-10-13 004553
Raise another PR with updated branch

**Comment by devarsheecodess** [comment]
@gauravsingh1281 ig there is no need of new PR, all checks have passed

**Comment by devarsheecodess** [comment]
image

**Pull request merged**
