### PR TITLE
[update]: updated footer section of the website to look more user friendly.

### LINKED ISSUE #204: [update]: Updating Footer Section for Consistent Styling and Content.
The current footer section's styling and content are not aligned with the overall website design.

Please assign this task to me under GSSOC and hacktoberfest as I will update the footer to ensure visual consistency with the rest of the site, including fonts, colors, and layout. Additionally, revise the content to match the website's theme and information structure.

Current Footer Section:

Screenshot 2024-10-05 173245

### PR DESCRIPTION
**Pull request by angadnagar**
## What this PR does?

I have updated the footer section of the website to make it more user-friendly and visually appealing. The following changes were made:

- Enhanced layout for better readability and structure.
- Improved color scheme, making the footer look more modern and aligned with the website's theme.
- Social media icons have been positioned more effectively for easier accessibility.

 Fixes #204 

## Screenshots
image

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @angadnagar please match the color with the website theme.

**Comment by angadnagar** [comment]
> Owner

you want that mint color in footer section not any other color than that?

**Comment by angadnagar** [comment]
Hey @gauravsingh1281 I have updated my code to match the background color of the footer section with the website theme as required by you.

**Comment by gauravsingh1281** [comment]
Hey @angadnagar please resolve the merge conflicts.

**Pull request merged**
