### PR TITLE
Improve Login registration functionality

### LINKED ISSUE #537: [BUG] Improve Login & Registration Functionality
### 🐛 Bug Report

**Describe the bug**
1. after login to the portal, the application redirected me to the admin panel 
there is no way to come back to the home page until we explicitly type the URL 
2. poor navbar UI, whenever I scroll, because of using a transparent navbar it seems like text is overlapping

---

**To Reproduce**
1. Scroll down to '....'

---

**Screenshots**
Screenshot 2024-10-27 122808

---

### PR DESCRIPTION
**Pull request by shibasarkar**
### 🚀 Pull Request

**Related Issue**  
If this pull request addresses an issue, link to it here (e.g., `Closes #537`).

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🐛 Bug fix  
- [x] 🚀 New feature  

---

**Screenshots (if applicable)**  

Screenshot 2024-11-03 114258

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by shibasarkar** [comment]
@gauravsingh1281  could you please look into this

**Comment by shibasarkar** [comment]
When a user is not logged into the system it shows two button
Screenshot
Screenshot 2024-11-05 194341
when a user is logged in it only shows the Logout
Screenshot
Screenshot 2024-11-03 114258

**Comment by gauravsingh1281** [comment]
@shibasarkar please resolve the merge conflicts.

**Comment by shibasarkar** [comment]
@gauravsingh1281 Resolve Conflicts

**Comment by shibasarkar** [comment]
@gauravsingh1281 resolved the issues but when I try to run it gives an error 
maybe someone changed something during my pull request 
Screenshot--
Screenshot 2024-11-07 190904

**Pull request closed without merging**
