### PR TITLE
Changed All Twitter Icons to X Icons

### PR DESCRIPTION
**Pull request by Bhanuprakash842**
I have changed all the Twitter icons to X Icons with the Updated code and removed conflicts.
Screenshot 2024-10-04 174301
Screenshot 2024-10-04 174233
Please merge my pull request under gssoc-ext,hacktoberfest

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @Bhanuprakash842 please resolve merge conflicts.

**Comment by gauravsingh1281** [comment]
@Bhanuprakash842 ?

**Comment by Bhanuprakash842** [comment]
I will resolve the conflicts now..

**Comment by gauravsingh1281** [comment]
Hey @Bhanuprakash842  your changes are not visible and your deploy preview has not been generated by netlify please pass all the checks by netlify.

**Pull request closed without merging**
