### PR TITLE
Implement hero section UI as shown in figma design - issue #216

### PR DESCRIPTION
**Pull request by kavya410004**
This pull request implements changes to the Hero section as per the Figma design for Rentalog.in. Here’s a summary of what has been done:

- **Updated Hero Section:** Made changes to the `Hero Section` to match the Figma design.
- **UI Enhancements:** Modified icons, background images, and colors to align with the Figma's aesthetic.
- **Responsive Design:** Ensured that the Hero section is fully responsive and looks good on all devices (mobile, tablet, desktop).

### Screenshots:
Below are the screenshots of figma design and Hero Section after changes:

- Figma design:
image

- Hero Section after changes:
image

### How this contributes to the project:
This update improves the UI/UX of the homepage, making it more visually consistent with the upcoming version as depicted in the Figma design.

### Related issues: 
Addresses #216 

Please review this PR.

### CODE REVIEW

**Comment by kavya410004** [comment]
@gauravsingh1281 Please check the PR and let me know if any changes are required. Thank you!

**Comment by gauravsingh1281** [comment]
Hey @kavya410004 thank you for your contribution use high quality image instead of this image which is used in figma design and also use your creativity to enhance the overall look.

**Comment by gauravsingh1281** [comment]
@kavya410004 ?

**Comment by kavya410004** [comment]
> @kavya410004 ?

Yes @gauravsingh1281

**Comment by gauravsingh1281** [comment]
@kavya410004 What your progress on this Pr ?

**Pull request closed without merging**
