### PR TITLE
Added a new rent calculation page

### PR DESCRIPTION
**Pull request by rana8aaskar**
### 🚀 Pull Request

**Description**  
A clear and concise description of the changes introduced in this pull request.

---

**Related Issue**  
If this pull request addresses an issue, link to it here (e.g., `Closes #123`).

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [ ] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  
Add screenshots or screen recordings to demonstrate the new feature or fix.

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [ ] I have tested my changes and ensured they work as expected.  
- [ ] I have added any necessary documentation or comments.  
- [ ] I have checked the existing issues and pull requests to avoid duplicates.  
- [ ] I have **starred this repository**.  
- [ ] I have reviewed my code for best practices and readability.  
- [ ] I have included any relevant tests (if applicable).

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by rana8aaskar** [comment]
@gauravsingh1281 please review and merge my pr.

**Comment by gauravsingh1281** [comment]
hey @rana8aaskar in the deployment preview navbar become distorted and  for the rent calculation features refer to its main website rentalog.in and try to fix this.

**Comment by rana8aaskar** [comment]
@gauravsingh1281 i resolved the issue.

**Comment by gauravsingh1281** [comment]
Hey @rana8aaskar no changes made by you according to the given instructions please resolve this.

**Pull request closed without merging**
