### PR TITLE
Create updated frontend

### PR DESCRIPTION
**Pull request by Aazib-at-hub**

### CODE REVIEW

**Comment by Aazib-at-hub** [comment]
@gauravsingh1281 here it is brother? Anything else?

**Comment by Aazib-at-hub** [comment]
@gauravsingh1281 Have you seen it brother?

**Comment by gauravsingh1281** [comment]
Hey, @Aazib-at-hub no changes are visible on the deployment preview please check.

**Comment by Aazib-at-hub** [comment]
@gauravsingh1281 i think let's leave it it looks good.

**Pull request closed without merging**
