### PR TITLE
added chatbot✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### 🚀 Pull Request

The chatbot is working perfectly!

https://github.com/user-attachments/assets/7e2ad82e-5e6d-46f3-83e7-debcc32e1a7b
@gauravsingh1281 can you please review this.
thank you!

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [X] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [X] I have tested my changes and ensured they work as expected.  
- [X] I have added any necessary documentation or comments.  
- [X] I have checked the existing issues and pull requests to avoid duplicates.  
- [X] I have **starred this repository**.  
- [X] I have reviewed my code for best practices and readability.  
- [X] I have included any relevant tests (if applicable).

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you review this please.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you review this please.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you review this please.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you review this please.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you please review this PR, it will be helpful.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you please review this PR, it will be helpful.
thank you.

**Comment by gauravsingh1281** [comment]
Hey @T-Rahul-prabhu-38, the chat icon is overlapping with the scroll to the top Icon fix this.

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281  the problem has been fixed. can you please review this PR , thank you!

Screenshot 2024-10-13 at 9 24 30 AM

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281 can you please review this PR. the issue has been resolved.

**Comment by gauravsingh1281** [comment]
@T-Rahul-prabhu-38 align the chat icon with the scroll to the top Icon in the same line in the vertical direction.

**Comment by T-Rahul-prabhu-38** [comment]
can i do that in a new PR

**Comment by gauravsingh1281** [comment]
Do in the same PR, update your branch first, and also reduce the size of the chat window.

**Comment by T-Rahul-prabhu-38** [comment]
Screenshot 2024-10-14 at 12 56 10 AM

is this better

**Comment by gauravsingh1281** [comment]
Screenshot 2024-10-14 010944

but changes not visible

**Comment by T-Rahul-prabhu-38** [comment]
yes the branch is updated

**Pull request merged**
