### PR TITLE
issue #307  fixed

### PR DESCRIPTION
**Pull request by gurramkarthiknetha**
fixed the responsiveness in the button in the small devices

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
@gurramkarthiknetha give proper PR description

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha give proper PR description

edited the the pr description

**Comment by gauravsingh1281** [comment]
@gurramkarthiknetha show me the screenshot of the changes you made and resolve the merge conflicts.

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha show me the screenshot of the changes you made and resolve the merge conflicts.

image

**Pull request merged**
