### PR TITLE
 solved #465 Added faq section

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### 🚀 Pull Request

**Description**  
Added faq section
---

**Related Issue**  
Added faq section
---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [x] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

https://github.com/user-attachments/assets/e5beddce-ceba-4cad-8175-a1f2163b0fec

**Screenshots (if applicable)**  
Add screenshots or screen recordings to demonstrate the new feature or fix.

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @KapuluruBhuvaneswariVspdbct  your changes are not visible and your deploy preview has not been generated by netlify please pass all the checks by netlify.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
image

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir,once please check the changes  and passed checks by netlify

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
it is visible to me like this sir (changed files)

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@gauravsingh1281 Sir,please check once
if everything is fine please add level3 label sir

**Review by gauravsingh1281 — APPROVED** [review]

**Pull request merged**
