### PR TITLE
chat open added in contact us section

### LINKED ISSUE #193: want to add a chat option in the contact section for whatsapp
i want to add the chat option for whatsapp in the contact us  section that redirect user to whatsapp on your given no. where they can chat with you easily.

### PR DESCRIPTION
**Pull request by ritikm31**
#193 issue  🚀 Pull Request

**Description**  
added the chat option in the contact us section which on clicking redirect user to chat on your given whatsapp number..

---

**Related Issue**  
If this pull request addresses an issue, link to it here (e.g., `Closes #193`).

---

**Type of Change**  
What kind of change does this pull request introduce?  

🚀 New feature

### CODE REVIEW

**Comment by ritikm31** [comment]
assigned me a label please for this pr.

**Comment by ritikm31** [comment]
also solved issue #192  here by adding appropriate font styles to the website kindly review them and please assgined both to a level labeled.

**Comment by gauravsingh1281** [comment]
@ritikm31 please update your branch with main branch.

**Comment by ritikm31** [comment]
but it's updated with main branch you can see on top

**Comment by ritikm31** [comment]
and if it's not can you tell me  how to do it

**Comment by gauravsingh1281** [comment]
In the deployment preview, it shows the older version of the website. You can update your code with the current branch or raise a new PR with the updated branch.

**Comment by ritikm31** [comment]
i checked all these are fixed i guess...or if it's not can you tell me step by step

**Comment by ritikm31** [comment]
it's a req to you

**Comment by ritikm31** [comment]
Appreciate for the merge.

**Pull request merged**
