### PR TITLE
Add Multilingual Support to Rentalog Web Application

### LINKED ISSUE #267: FEAT: Add Google Translator for Multi-language Support in Rentalog
### Description:
We need to integrate Google Translator into the Rentalog web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Tasks:

	1.	Investigate the Google Translator API or other suitable translation tools.
	2.	Integrate the translator into the main layout of the application.
	3.	Ensure translation is available for all pages, including:
	•	Home page
	•	Login/Registration pages
	•	Dashboard
	•	Property Listings
	•	User Profile
	•	All other relevant sections
	4.	Add a language selector dropdown to the header/footer for easy language switching.
	5.	Test translations to ensure proper formatting and layout across all languages.

### Acceptance Criteria:

	•	Users should be able to translate any page to their selected language using the Google Translator integration.
	•	The layout and styling of pages should not break when the content is translated.
	•	The language selector should be accessible and functional on all pages.

### Program: GSSOC-ext and hacktoberfest
** Please add LEVEL 3 to the issue**

### PR DESCRIPTION
**Pull request by IkkiOcean**
### 🚀 Pull Request

**Description**  
This PR introduces multilingual support to the Rentalog web application, allowing users to interact with the platform in their preferred language. The implementation enhances the user experience and accessibility, ensuring that our application is more inclusive for a diverse audience.

---

**Related Issue**  
Closes #267 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🚀 New feature  

---

**Screenshots (if applicable)**  

https://github.com/user-attachments/assets/b27075dc-b650-484d-860f-668746f61a10

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  

---

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@gauravsingh1281 kindly review and merge soon.

**Comment by gauravsingh1281** [comment]
Hey @IkkiOcean, change the translate icon's position to the top right and please resolve the merge conflicts.

**Comment by IkkiOcean** [comment]
> Hey @IkkiOcean, change the translate icon's position to the top right and please resolve the merge conflicts.



> Hey @IkkiOcean, change the translate icon's position to the top right and please resolve the merge conflicts.

done!

https://github.com/user-attachments/assets/07d38357-a083-4cc7-8579-4cbc8b5cce09

**Comment by gauravsingh1281** [comment]
top right means in the navbar

**Pull request closed without merging**
