### PR TITLE
added blurred background images

### PR DESCRIPTION
**Pull request by coderashhar**
### 🚀 Pull Request

**Description**  
Added blurred background images to OUR SERVICES ARE AVAILABLE IN section.

---

**Related Issue**  
Closes issue #320 .

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [ x ] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ x ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  

BEFORE
Screenshot 2024-10-13 at 2 53 56 PM

AFTER
Screenshot 2024-10-13 at 11 11 11 PM

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [ x ] I have tested my changes and ensured they work as expected.  
- [ x ] I have added any necessary documentation or comments.  
- [ x ] I have checked the existing issues and pull requests to avoid duplicates.  
- [ x ] I have **starred this repository**.  
- [ x ] I have reviewed my code for best practices and readability.  
- [ x ] I have included any relevant tests (if applicable).

---

### CODE REVIEW

**Comment by coderashhar** [comment]
@gauravsingh1281 kindly merge my PR

**Comment by coderashhar** [comment]
@gauravsingh1281 kindly review and merge my PR.

**Comment by coderashhar** [comment]
@gauravsingh1281 kindly check my PR and merge it.

**Comment by gauravsingh1281** [comment]
Hey @coderashhar the changes you made is not looking good try to make it more better.

**Comment by coderashhar** [comment]
@gauravsingh1281 should I decrease the amount of blur?

**Comment by gauravsingh1281** [comment]
@coderashhar ?

**Comment by coderashhar** [comment]
@gauravsingh1281 I'll update it in a bit

**Comment by coderashhar** [comment]
@gauravsingh1281  I have decreased the blur, Kindly review it .

BEFORE 
before

AFTER
after

**Comment by gauravsingh1281** [comment]
update your branch with main branch because navbar not looks good.

**Pull request closed without merging**
