### PR TITLE
fix chatbot

### PR DESCRIPTION
**Pull request by amanver45**
#545
### 🚀 Pull Request

 chatbot is now working fine

**Related Issue**  
#545 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🐛 Bug fix  
- [ ] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ 

https://github.com/user-attachments/assets/85f68d93-57c3-4693-a3f6-81595ca57722

Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---\

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.

### CODE REVIEW

**Comment by amanver45** [comment]
@Gaurav075 pkls check

**Comment by gauravsingh1281** [comment]
@amanver45 chat bot is not visible in the deployment preview fix this.

**Comment by amanver45** [comment]
@gauravsingh1281 check

**Comment by gauravsingh1281** [comment]
Screenshot 2024-11-02 153922
@amanver45 chatbot not visible fix this.

**Comment by amanver45** [comment]
Screenshot 2024-11-02 155402
@gauravsingh1281 sir its working fine pls wait for sometime maybe its loadijng if not working i should rsise new pr

**Comment by gauravsingh1281** [comment]
Hey @amanver45  , your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify.

**Comment by amanver45** [comment]
@gauravsingh1281  i close this one and raise newpr

**Pull request closed without merging**
