### PR TITLE
Added an attractive modal alert

### LINKED ISSUE #383: [FEATURE] Contact alert should be bit attractive
🚀 Feature Request

Description
Implement a modal-based alert box that appears when users click the "Submit" button on the contact page. This modal should display a message indicating the successful submission of the form in an attractive and engaging manner.

Problem Statement
Currently, after clicking the submit button on the contact page, users don’t get a clear, visually appealing confirmation that their form was submitted successfully. This can lead to confusion about whether the submission went through.

Proposed Solution

    When the submit button is clicked, trigger a modal with a message like "Thank you for reaching out! We will get back to you shortly."
    The modal should be attractively styled with animations to grab the user's attention.
    Include a close button to allow users to dismiss the modal, or automatically close it after a few seconds.

image

### PR DESCRIPTION
**Pull request by PulkitShubham**
---

### 🚀 Pull Request

**Description**  
This pull request introduces an enhanced user experience in the Contact Form component by implementing a modal confirmation message with an appealing tick icon upon successful form submission. The modal's design has also been improved for better visual feedback.

---

**Related Issue**  
Closes #383 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [x] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [x] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  

image

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

**Additional Context**  
This update focuses on improving the user interaction experience by providing immediate feedback after form submission. The modal's design is more engaging, and the tick icon adds a sense of accomplishment for the user.

---

### CODE REVIEW

**Comment by PulkitShubham** [comment]
@gauravsingh1281 Kindly check the PR...I have completed the assigned task

**Comment by PulkitShubham** [comment]
@gauravsingh1281 Please review my PR

**Comment by PulkitShubham** [comment]
@gauravsingh1281 Kindly check my PR

**Comment by gauravsingh1281** [comment]
Hey @PulkitShubham  your changes are not visible and your deploy preview has not been generated by netlify please pass all the checks by netlify.

**Pull request closed without merging**
