### PR TITLE
Changed FAQ from Home Page

### PR DESCRIPTION
**Pull request by namansinghrana**
### 🚀 Pull Request

**Description**  
A clear and concise description of the changes introduced in this pull request.

---

**Related Issue**  
If this pull request addresses an issue, link to it here (e.g., `Closes #123`).

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [ ] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [x] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  
image
---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @namansinghrana , your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify.

**Comment by namansinghrana** [comment]
Ok Sir,
Let me recheck thoroughly.

**Comment by gauravsingh1281** [comment]
Hey @namansinghrana everything is messed up in the deployment preview fix this.

**Comment by namansinghrana** [comment]
Done merge conflicts are resolved and the minimalist FAQ is implemented.

**Comment by namansinghrana** [comment]
Sir @gauravsingh1281,
Now you can check the changes are visible upon the home page.
And the recent merge conflicts are resolved.

**Pull request merged**
