### PR TITLE
Enhance User Testimonial Section

### PR DESCRIPTION
**Pull request by Devaki01**
This is with reference to issue #179 . I have made the changes as proposed in my issue. Please review it and let me know if any changes are required.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @Devaki01 your changes are not visible and your deploy preview has not been generated by netlify please pass all the checks by netlify.

**Comment by Devaki01** [comment]
> @Devaki01 ?

I am not sure how to pass the checks. Will u pls guide me through the same?

**Comment by gauravsingh1281** [comment]
Screenshot 2024-10-09 234115


There seems to be an error in your code, so please try to find it, fix it, and raise the pr again.

**Comment by Devaki01** [comment]
> Screenshot 2024-10-09 234115
> There seems to be an error in your code, so please try to find it, fix it, and raise the pr again.

ok..will do. thanks

**Comment by gauravsingh1281** [comment]
@Devaki01 ?

**Pull request closed without merging**
