### PR TITLE
added missing google icon

### PR DESCRIPTION
**Pull request by Sameeratweb**
Google icon isn't loading, and displaying the alt text instead.
The issue is Fixed with the proper icon.
I hope to merge it.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @Sameeratweb issue not resolved please share screenshot.

**Comment by Sameeratweb** [comment]
Screenshot 2024-10-04 144733
please check it once again and let me know whether issue is resolved.

**Comment by gauravsingh1281** [comment]
hey @Sameeratweb you only fixed the issue of the login page do the same for the register page also.

**Comment by Sameeratweb** [comment]
I have added the Google icon for both the login and register pages.
I hope to merge it.

**Pull request merged**
