### PR TITLE
Improved UI for the Rentalog Landing Page

### PR DESCRIPTION
**Pull request by T-Fathima**
**This PR introduces the following UI changes:
solved issue #224** 

**Navbar Background and Style Updates:**
Added a new background color to the navbar for better contrast and readability.
Updated the spacing and alignment for a cleaner look.
Changed hover effects to enhance interactivity.

**Rentalog Page Enhancements:**
Improved the layout and visual design of the Rentalog page to make it more user-friendly.
Added additional styling to buttons and interactive elements for a more modern feel.

**Request:**
Please review the changes and provide any feedback. Once approved, kindly merge this PR. @gauravsingh1281 

image

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @T-Fathima please resolve the merge conflicts and enhance the design with updated branch code.

**Comment by gauravsingh1281** [comment]
@T-Fathima ?

**Comment by T-Fathima** [comment]
> @T-Fathima ?

Resolved the conflicts. Please check.

**Comment by gauravsingh1281** [comment]
Hey @T-Fathima  your changes are not visible and your deploy preview has not been generated by netlify please pass all the checks by netlify. and try to enhance design .

**Pull request closed without merging**
