### PR TITLE
Added feedback Form

### PR DESCRIPTION
**Pull request by TBorundia**
### 🚀 Pull Request

**Description**  
Added the feedback form with validation and submission pop-up.

---

**Related Issue**  
Closes: #394

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [X] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  

https://github.com/user-attachments/assets/2811a6bb-e5fc-468e-b94a-79ed4c253713

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [X] I have tested my changes and ensured they work as expected.  
- [X] I have checked the existing issues and pull requests to avoid duplicates.  
- [X] I have **starred this repository**.  
- [X] I have reviewed my code for best practices and readability.  
- [X] I have included any relevant tests (if applicable).

### CODE REVIEW

**Comment by TBorundia** [comment]
@gauravsingh1281 Sir, Please review this PR. Thank You!!

**Comment by TBorundia** [comment]
@gauravsingh1281 , Sir, Please review this PR. Thank You!!

**Comment by gauravsingh1281** [comment]
hey @TBorundia please resolve the merge conflicts.

**Comment by TBorundia** [comment]
@gauravsingh1281 , Solved

**Comment by gauravsingh1281** [comment]
Hey @TBorundia , your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify. and resolve the merge conflicts.

**Comment by TBorundia** [comment]
@gauravsingh1281 , I shall work on it !!

**Comment by gauravsingh1281** [comment]
@TBorundia ?

**Comment by TBorundia** [comment]
@gauravsingh1281 ,
Due to my exam, it's taking me more time, but I will complete it by today or, at the latest, tomorrow.
Sorry for this !!

**Comment by TBorundia** [comment]
@gauravsingh1281 , Added feedback Form. Please review it now.


https://github.com/user-attachments/assets/82c244a4-4928-4872-82e7-1c7ad74c088f

**Pull request merged**
