### PR TITLE
Added Animeted Pre Loader

### LINKED ISSUE #405: [FEATURE] : Adding animeted Pre Loader
### Feature Description

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

### Use Case

1. Initial Load Times: Users might experience slight delays due to larger assets or slow networks. The preloader would fill this gap, making the waiting time feel more fluid and professional.
2. First-Time Users: First-time users of the site may have slower load times as assets like images and scripts are fetched for the first time. The preloader would reassure them that content is being loaded.

### Benefits

1. Improved User Experience: Users won’t be left staring at a blank screen during loading times, which could otherwise lead to frustration or abandonment.
2. Enhanced Aesthetics: An animated preloader can add a professional touch, maintaining user engagement with an interesting visual instead of a plain loading bar.
3. Branding Opportunity: The preloader animation can incorporate elements of the website’s branding, such as its logo or color palette, helping to reinforce brand identity.

## Below one is sample video
https://github.com/user-attachments/assets/ab4e1fc8-54e5-4c2f-b58a-db67299b32af

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
### 🚀 Pull Request

**Description**  
Animeted text preloader added which looks very good and enhanced user experience

---

**Related Issue**  
Closes #405 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [ ] 🐛 Bug fix  
- [x] 🚀 New feature  
- [ ] 📄 Documentation update  
- [ ] 🛠️ Code improvement/refactor  
- [ ] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  

https://github.com/user-attachments/assets/f1eaaeea-0bc4-4c7d-a584-0335c45e3048

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
@AbhijitMotekar99 , your changes are not visible, and your deploy preview has not been generated by Netlify. Please pass all the checks by Netlify.

**Comment by AbhijitMotekar99** [comment]
Hey @gauravsingh1281 
Now check I resolved the problem and Pass All checks.

**Comment by gauravsingh1281** [comment]
@AbhijitMotekar99 resolve merge conflicts.

**Comment by AbhijitMotekar99** [comment]
Hey @gauravsingh1281 
All conflicts resolved now you can merge it

**Pull request merged**
