### PR TITLE
I had update some of the properties.  

### PR DESCRIPTION
**Pull request by Dipanita45**
… Plaease review and label me.

### 🚀 Pull Request

**Description**  
Changes the font size, text align, colour, transition and all this type of css properties to make more attractive

---

**Related Issue**  
#283 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [no ] 🐛 Bug fix  
- [no] 🚀 New feature  
- [no] 📄 Documentation update  
- [yes ] 🛠️ Code improvement/refactor  
- [ yes] 🖼️ UI/UX update  
- [ no] Other (please specify)

---

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [ yes] I have tested my changes and ensured they work as expected.  
- [yes ] I have added any necessary documentation or comments.  
- [ no] I have checked the existing issues and pull requests to avoid duplicates.  
- [ yes] I have **starred this repository**.  
- [ yes] I have reviewed my code for best practices and readability.  
- [ ] I have included any relevant tests (if applicable).

---

Please review and label me

### CODE REVIEW

**Comment by Dipanita45** [comment]
Thank you for the chance. Please review and label me

**Comment by gauravsingh1281** [comment]
Hey @Dipanita45 please resolve the merge conflicts.

**Comment by Dipanita45** [comment]
Okay sir
How to do it sir

**Comment by Dipanita45** [comment]
`I had resolve the merge conflicts`
Sorry for the incovenience
Thank you @gauravsingh1281 sir
Please review my pull request and label me

**Comment by Dipanita45** [comment]
I had check  
Please review the  pull request
Thank you @gauravsingh1281 sir for the support

**Comment by gauravsingh1281** [comment]
Hey @Dipanita45 please share the screenshot/screen recording of changes you made because in this PR changes are not visible.  or you can create new PR.

**Pull request closed without merging**
