### PR TITLE
Changed UI for translator

### PR DESCRIPTION
**Pull request by Antima2004**
### 🚀 Pull Request

**Description**  
Changed the UI for the translator

---

**Related Issue**  
If this pull request addresses an issue, link to it here (e.g., `Closes #123`).

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🐛 Bug fix  
- [x] 🚀 New feature  
- [ ] 📄 Documentation update  
- [x] 🛠️ Code improvement/refactor  
- [x] 🖼️ UI/UX update  
- [ ] Other (please specify)

---

**Screenshots (if applicable)**  
Before:
Screenshot 2024-11-03 115632

After:
Screenshot 2024-11-03 115558

---

**Checklist**  
Please ensure the following tasks are complete before submitting the pull request:  
- [x] I have tested my changes and ensured they work as expected.  
- [x] I have added any necessary documentation or comments.  
- [x] I have checked the existing issues and pull requests to avoid duplicates.  
- [x] I have **starred this repository**.  
- [x] I have reviewed my code for best practices and readability.  
- [x] I have included any relevant tests (if applicable).

---

**Additional Context**  
Add any other relevant information or context about the pull request here.

### CODE REVIEW

**Comment by Antima2004** [comment]
@gauravsingh1281 please merge this pr and give feedback.

**Comment by Antima2004** [comment]
Ok

**Comment by Antima2004** [comment]
@gauravsingh1281 please help me what i have to do to solve this conflict.

**Comment by Antima2004** [comment]
@gauravsingh1281 I have resolved the conflict

**Comment by gauravsingh1281** [comment]
@Antima2004 not resolved please fix this.

**Comment by Antima2004** [comment]
Ok

**Pull request closed without merging**
