### PR TITLE
Enhance Contact Form with Hover Effects and Responsive Design Adjustments

### PR DESCRIPTION
**Pull request by neeru24**
## **Pull Request Title:**
Enhance Contact Form with Hover Effects and Responsive Design Adjustments

## **Description:**
This PR includes updates to improve the user experience on the contact form through hover effects, size transitions, and responsive design changes.

### **Key Changes:**

1. **Hover Effect with Size Transition:**
   - **Form Input Fields:** Introduced a hover effect on text input fields and the `textarea`. When hovered, fields scale slightly (`scale(1.05)`), providing users a visual focus cue.
   - **Glow Effect:** Added a soft green glow to input fields on hover using `box-shadow: 0 0 5px 1px rgba(0, 255, 0, 0.5)`.
   - **Submit Button Hover:** The submit button now has a hover effect, growing in size (`scale(1.05)`) with a similar green glow for better interaction feedback.

2. **Reduced Glow Intensity:**
   - Lowered the intensity of the glow effect by adjusting the `box-shadow` spread to `5px` and decreasing opacity to ensure a more subtle effect without being distracting.

3. **Responsive Design Improvements:**
   - Made hover effects smooth across devices by retaining responsive behavior for all form fields.
   - The form's layout stacks vertically on smaller screens for better usability.

4. **Form Input Enhancements:**
   - The border color of input fields changes on hover to a vibrant green (`border-color: #00ff00`).
   - Kept a smooth transition with `transition: all 0.3s ease-in-out` on both inputs and the submit button.

5. **Retained Original CSS Structure:**
   - Preserved existing styling, ensuring new effects integrate seamlessly with the previous layout.

fixes: #445

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @neeru24  your changes are not visible and your deployment preview has not been generated by netlify please pass all the checks by netlify.

**Comment by neeru24** [comment]
> Hey @neeru24  your changes are not visible and your deployment preview has not been generated by netlify please pass all the checks by netlify.

Okay

**Comment by neeru24** [comment]
> Hey @neeru24 your changes are not visible and your deployment preview has not been generated by netlify please pass all the checks by netlify.

@gauravsingh1281 I tried to do so, but I  do not know why preview is not getting generated and the file has no merge conflicts. If you could help me, then kindly let me know or please merge it as the file have no conflicts.
image

**Comment by gauravsingh1281** [comment]
@neeru24 ?

**Comment by neeru24** [comment]
I was trying to figure it out, but it was not getting resolved so I closed it.

**Pull request closed without merging**
