### PR TITLE
background-images & 3-d hover effects added to the 'Our Services' cards

### LINKED ISSUE #455: [FEATURE] Add background images to the 'Our Services' cards
I want to add background images to the each of the 'Our Services Includes' section cards and add some box shadow on hover for 3-d effects

Proposed Solution
I want to add background images to the each of the 'Our Services Includes' section cards and add some box shadow on hover for 3-d effects.
This will enhance the UI of the webpage.

Do you want to work on this issue?
Yes

@gauravsingh1281 Kindly assign me this issue with gssoc-ext tag and a relevant level tag

### PR DESCRIPTION
**Pull request by Edasgh**
### 🚀 Pull Request

**Description**  
Added background-images to each of the 'Our Services' cards and added box-shadows on-hover to give 3-d effects

---

**Related Issue**  
Closes #455 

---

**Type of Change**  
What kind of change does this pull request introduce?  
- [x] 🚀 New feature  
- [x] 🖼️ UI/UX update  

**Screenshots**
Screenshot 2024-10-25 225222
Screenshot 2024-10-25 225238

### CODE REVIEW

**Comment by Edasgh** [comment]
@gauravsingh1281 kindly review this PR

**Comment by Edasgh** [comment]
@gauravsingh1281 Sir.... please review this PR

**Comment by gauravsingh1281** [comment]
@Edasgh in our services section, the background image is missing in the deployment preview and it looks dark please match the design with website theme.

**Comment by Edasgh** [comment]
> @Edasgh in our services section, the background image is missing in the deployment preview and it looks dark please match the design with website theme.

Ok

**Comment by Edasgh** [comment]
> @Edasgh in our services section, the background image is missing in the deployment preview and it looks dark please match the design with website theme.

@gauravsingh1281  This issue is now resolved , check the PR

**Pull request merged**
