### PR TITLE
Added Darkmode

### PR DESCRIPTION
**Pull request by AsifQamar**
dark mode added

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
Hey @AsifQamar no changes are visible and add an option to toggle dark and light mode.

**Comment by AsifQamar** [comment]
Ok wait

**Comment by gauravsingh1281** [comment]
?

**Comment by AsifQamar** [comment]
> ?

i have checked the code its correct dont know why its not working

**Comment by gauravsingh1281** [comment]
> > ?
> 
> i have checked the code its correct dont know why its not working

there is no option to switch between dark and light mode.

**Comment by AsifQamar** [comment]
> > > ?
> > 
> > 
> > i have checked the code its correct dont know why its not working
> 
> there is no option to switch between dark and light mode.

I have added the code for toggle button don't know why it's not showing

**Comment by gauravsingh1281** [comment]
close this pr and raise another pr with update branch.

**Pull request closed without merging**
